development:
  adapter: postgresql
  encoding: unicode
  pool: 25
  database: vgPortal
  username: apdev
  password: apdev123
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  pool: 25
  database: vgPortal-test
  username: apdev
  password: apdev123
  host: localhost
  template: template0

