production:
  adapter: postgresql
  encoding: unicode
  pool: 25
  database: <%= ENV["PG_DATABASE"] %>
  username: <%= ENV["PG_USERNAME"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  template: template0
  host: <%= ENV["PG_HOST"] %>
  port: <%= ENV["PG_PORT"] %>

development:
  adapter: postgresql
  encoding: unicode
  pool: 25
  database: vgPortal
  username: postgres
  password: 123456
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  pool: 25
  database: vgPortal-test
  username: apdev
  password: apdev123
  host: localhost
  template: template0

