# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b5686f68355d56b7185604563b683782fc0ed3e3c4122a8aec58c495b0c85563123994069b4ee4b4175e74193b923d8c84eae97c36651fdcaf6d8e11c8694e3

test:
  secret_key_base: 78e4a602f1bd4abbb66b1b9e20c84a6e8dd1666791e52c9b5be6a45f5e578709bf616bc23aab1d14df2ba5909a22f262f686525aed6a6f8a2579eb01d4e6c496

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8b5686f68355d56b7185604563b683782fc0ed3e3c4122a8aec58c495b0c85563123994069b4ee4b4175e74193b923d8c84eae97c36651fdcaf6d8e11c8694e3